### ISSUE TITLE
[Bootcamp] Sort categories alphabetically (admin side)

### ISSUE THREAD

**Issue by michellejli77** [ScottyLabs/lost-and-found#38]
### Task Brief
- When admin add/edit items, they see a list of categories for each item
- Instead of listing the categories in an arbitrary order, sort the categories in alphabetic order
- This is how it looks like right now:
<img width="564" alt="Screenshot 2023-09-29 at 7 11 08 PM" src="https://github.com/ScottyLabs/lost-and-found/assets/70723676/350b3b8a-87e1-4c54-95d2-20d17a483174">

### Expected Deliverables

Fix the category order

### Estimated Completion Time

30 minutes

### Reviewers

@michellejli77 
@Adrastopoulos

**Comment by axgu** [comment]
Closed by #75
