### ISSUE TITLE
[Bootcamp] Update "Retrieve From" (admin side)

### ISSUE THREAD

**Issue by michellejli77** [ScottyLabs/lost-and-found#62]
### Task Brief

Currently, the "Retrieve From" field lists a ton of different locations, but we only want it to show Cohon (because that is our only current pick-up location). If it's too complex to remove the other locations, we should make the default location Cohon so admin don't have to scroll and select it every time.
<img width="569" alt="Screenshot 2023-11-18 at 4 04 53 PM" src="https://github.com/ScottyLabs/lost-and-found/assets/70723676/238c3f58-10e5-456a-a02e-7e82cdaf8e98">

### Expected Deliverables

Change "Retrieve From" to have CUC as the default location, or the only location.

### Estimated Completion Time

1 hour

### Reviewers

@mich

**Comment by axgu** [comment]
#77
